# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(430, 260, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calcButton.setFont(font)
        self.calcButton.setObjectName("calcButton")
        self.height = QtWidgets.QLabel(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(110, 70, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.height.setFont(font)
        self.height.setObjectName("height")
        self.weight = QtWidgets.QLabel(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(110, 180, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.weight.setFont(font)
        self.weight.setObjectName("weight")
        self.inputh = QtWidgets.QTextEdit(self.centralwidget)
        self.inputh.setGeometry(QtCore.QRect(250, 90, 121, 51))
        self.inputh.setObjectName("inputh")
        self.inputw = QtWidgets.QTextEdit(self.centralwidget)
        self.inputw.setGeometry(QtCore.QRect(250, 180, 121, 51))
        self.inputw.setObjectName("inputw")
        self.bmi = QtWidgets.QLabel(self.centralwidget)
        self.bmi.setGeometry(QtCore.QRect(120, 270, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bmi.setFont(font)
        self.bmi.setObjectName("bmi")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(430, -10, 381, 331))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.dispbmi = QtWidgets.QTextBrowser(self.centralwidget)
        self.dispbmi.setGeometry(QtCore.QRect(240, 270, 131, 51))
        self.dispbmi.setObjectName("dispbmi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calcButton.setText(_translate("MainWindow", "Calculate BMI"))
        self.height.setText(_translate("MainWindow", "Height:"))
        self.weight.setText(_translate("MainWindow", "Weight:"))
        self.bmi.setText(_translate("MainWindow", "BMI: "))
        self.info.setText(_translate("MainWindow", "BMI Categories:\n"
"Underweight = <18.5\n"
"Normal weight = 18.5–24.9\n"
"Overweight = 25–29.9\n"
"Obesity = BMI of 30 or greater"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
